apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rtch21tdq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rtch21tdq-python 
  name: rtch21tdq-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rtch21tdq-python
    weight: 100 
