apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rtch21tdq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rtch21tdq-python 
  name: rtch21tdq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rtch21tdq-python 
